In [3]:
"""
PROYECTO PROE
Este código se utiliza para calibrar la cámara del sistema de visión, para ejecutarlo se debe tener instalada la librería
openCV y tener al menos 10 imágenes de calibración en la misma carpeta. 
"""

import cv2
import cv2 as cv
import numpy as np
import os
import glob

# Define las dimensiones del del tablero
CHECKERBOARD = (6,9) #Número filas de vértices pr número de columnas de vértices
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 40, 0.001) #cada cuadrado del patrón mide 40 mm

# Guarda los puntos 3D del tablero
objpoints = []
# Guarda los puntos 2D del tablero
imgpoints = [] 


# Define las coordenadas globales para los puntos en 3D
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None

#Dirección de las imagénes de calibración
images = glob.glob('./Imagenes_Calibracion_Nueva_Sala/*.jpg') 
for fname in images: 
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Encuentra las esquinas del patrón de calibración
    # Cuando se encuentran las esquinas deseadas ret = True
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
    
    """
    Si se detecta el número deseado de esquinas,
    refinamos las coordenadas de píxeles y mostramos
    ellos en las imágenes del tablero de ajedrez
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
        
        imgpoints.append(corners2)

        # Dibuja los puntos en las esquinas
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
    
    cv2.imshow('img',img)
    cv2.waitKey(0)

cv2.destroyAllWindows()

h,w = img.shape[:2]

"""
Realización de la calibración de la cámara 
pasando el valor de puntos 3D conocidos (objpoints)
y las correspondientes coordenadas de píxeles de las
esquinas detectadas (imgpoints)
"""

#Obtiene la matriz de calibración, traslación y rotación
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

#Se elimina la distorsión en una imagen para verificar
img = cv.imread('2022-03-16_12-54-52.jpg')
h,  w = img.shape[:2]
newcameramtx, roi = cv.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

#Elimina distorsión
dst = cv.undistort(img, mtx, dist, None, newcameramtx)
# recorta la imagen
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png', dst) #Guarda la imagen sin distorsión

# Se guardan las matrices obtenidas de la calibración
np.savetxt("dist.txt", dist)
np.savetxt("cameraMatrix.txt", mtx)
np.savetxt("newCameraMatrix.txt", newcameramtx)
np.savetxt("roi.txt", roi)

#Verifica la exactitud de los valores encontrados
mean_error = 0
for i in range(len(objpoints)):
    imgpoints2, _ = cv.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
    error = cv.norm(imgpoints[i], imgpoints2, cv.NORM_L2)/len(imgpoints2)
    mean_error += error
print( "total error: {}".format(mean_error/len(objpoints)) )


#Imprime los parámetros de calibración
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)


total error: 0.0552641673772373
Camera matrix : 

[[1.76110961e+04 0.00000000e+00 1.63712810e+03]
 [0.00000000e+00 1.74358206e+04 9.60242471e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist : 

[[ 5.82569327e+00 -3.02796880e+02  7.31427186e-02  4.22964102e-02
   4.17368506e+03]]
rvecs : 

(array([[0.2373159 ],
       [0.08720518],
       [1.58654717]]), array([[0.08619746],
       [0.21020659],
       [1.60826181]]), array([[-0.16137462],
       [-0.14761612],
       [ 1.56151594]]), array([[-0.19629821],
       [-0.330661  ],
       [ 1.60704311]]), array([[-0.09633312],
       [-0.26215948],
       [-0.02436586]]), array([[-0.08118751],
       [-0.13059568],
       [ 0.64144199]]), array([[0.13795063],
       [0.08737275],
       [2.19499252]]), array([[-0.19496459],
       [-0.15990929],
       [-3.09396098]]))
tvecs : 

(array([[-22.61916839],
       [ 11.38835958],
       [443.16108821]]), array([[-20.69998925],
       [-21.54232935],
       [447.54438205]]), array([[  1